ALTER TYPE "RuleCategory" ADD VALUE IF NOT EXISTS 'QUIET_HOURS';
ALTER TYPE "RuleCategory" ADD VALUE IF NOT EXISTS 'FURNISHING';
ALTER TYPE "RuleCategory" ADD VALUE IF NOT EXISTS 'CUSTOM';

ALTER TABLE "PropertyRule"
ADD COLUMN "selectedValue" TEXT;