ALTER TYPE "TemplateType" ADD VALUE IF NOT EXISTS 'SCREENING_INVITE';
ALTER TYPE "TemplateType" ADD VALUE IF NOT EXISTS 'TOUR_INVITE';
ALTER TYPE "TemplateType" ADD VALUE IF NOT EXISTS 'HOUSE_RULES_ACKNOWLEDGMENT';
ALTER TYPE "TemplateType" ADD VALUE IF NOT EXISTS 'ONBOARDING';
ALTER TYPE "TemplateType" ADD VALUE IF NOT EXISTS 'WAITLIST_NOTICE';